// Dữ liệu lộ trình IELTS 5.0 → 7.0 (tuần 0 + 32 tuần): cấu trúc, link và đề bài.
// Chữ hiển thị theo ngôn ngữ (tên tuần, ghi chú ngữ pháp, nhật ký...) nằm trong js/content/<mã ngôn ngữ>.js.
// Mọi link đã được kiểm tra mở được ngày 21/09/2026. Chạy lại `python3 tools/check-links.py` để kiểm tra định kỳ.

const BC = "https://learnenglish.britishcouncil.org/free-resources/";
const BBC = "https://www.bbc.co.uk/learningenglish/english/features/";

// Mỗi tài liệu: [tiêu đề, url, nguồn, chi tiết]. "chi tiết" là số phút, hoặc một mã loại
// (vd "lesson", "pdf") được dịch trong locales/*.js → res.kind.<mã>.
const yt = (id, title, source, minutes) => [title, "https://www.youtube.com/watch?v=" + id, source, minutes];
const bc = (path, title, kind = "lesson") => [title, BC + path, "British Council", kind];
const six = (path, title) => ["6 Minute English: " + title, BBC + path, "BBC", "six"];
const tim = (ep, title) => ["Tim's Pronunciation Workshop: " + title, BBC + "pronunciation/tims-pronunciation-workshop-ep-" + ep, "BBC", 3];

const R = {
  // ---------- Công cụ & tài liệu chung ----------
  notebook: ["English Notebook (your flashcards)", "#cards", "", "self"],
  anki: ["Anki (spaced-repetition flashcards)", "https://apps.ankiweb.net/", "", "anki"],
  oxfordDict: ["Oxford Learner's Dictionaries", "https://www.oxfordlearnersdictionaries.com/", "", "dict"],
  collocDict: ["Oxford Collocation Dictionary", "https://m.freecollocation.com/", "", "colloc"],
  ox3000: ["Oxford 3000 & 5000", "https://www.oxfordlearnersdictionaries.com/wordlists/oxford3000-5000", "", "ox3000"],
  opal: ["OPAL — Oxford Phrasal Academic Lexicon", "https://www.oxfordlearnersdictionaries.com/wordlists/opal", "", "opal"],
  famTest: ["IELTS familiarisation test (official, on computer)", "https://cdielts.gelielts.com/", "", "famTest"],
  famInfo: ["About the computer familiarisation test", "https://takeielts.britishcouncil.org/prepare/ielts-free-practice-mock-tests/ielts-familiarisation-test", "British Council IELTS"],
  fmtL: ["Listening test format", "https://ielts.org/take-a-test/test-types/ielts-academic-test/ielts-academic-format-listening", "ielts.org"],
  fmtR: ["Reading test format", "https://ielts.org/take-a-test/test-types/ielts-academic-test/ielts-academic-format-reading", "ielts.org"],
  fmtW: ["Writing test format", "https://ielts.org/take-a-test/test-types/ielts-academic-test/ielts-academic-format-writing", "ielts.org"],
  fmtS: ["Speaking test format", "https://ielts.org/take-a-test/test-types/ielts-academic-test/ielts-academic-format-speaking", "ielts.org"],
  bdW: ["Writing band descriptors (official marking criteria)", "https://ielts.org/cdn/ielts-guides/ielts-writing-band-descriptors.pdf", "ielts.org", "pdf"],
  bdS: ["Speaking band descriptors (official marking criteria)", "https://ielts.org/cdn/ielts-guides/ielts-speaking-band-descriptors.pdf", "ielts.org", "pdf"],
  diff67: ["Differences between band 6 and band 7 in Writing & Speaking", "https://ielts.org/news-and-insights/differences-between-ielts-6-and-7-for-productive-skills", "ielts.org", "article"],
  sampleQ: ["Official IELTS Academic sample questions", "https://ielts.org/take-a-test/preparation-resources/sample-test-questions/academic-test", "", "sampleQ"],
  speakSample: ["Official Speaking sample tasks", "https://ielts.org/cdn/ielts-downloadable-assets/ielts-sample-tests/ielts-speaking-sample-tasks-2023.pdf", "", "speakSample"],
  writeSample: ["Sample Writing answers with band scores & examiner comments", "https://ielts.org/cdn/computer-delivered-sample-tests-academic-writing/ielts-academic-writing-example-responses-to-parts-1-and-2-with-band-scores-and-examiner-comments.pdf", "ielts.org", "pdf"],
  liz100: ["100 IELTS Essay Questions (by topic)", "https://ieltsliz.com/100-ielts-essay-questions/", "IELTS Liz"],
  lizP1: ["Speaking Part 1 Topics & Questions", "https://ieltsliz.com/ielts-speaking-part-1-topics/", "IELTS Liz"],
  lizP2: ["Speaking Part 2 Topics", "https://ieltsliz.com/ielts-speaking-part-2-topics/", "IELTS Liz"],
  lizT1: ["Writing Task 1: tips & model answers", "https://ieltsliz.com/ielts-writing-task-1-lessons-and-tips/", "IELTS Liz"],
  lizT2: ["Writing Task 2: tips & model essays", "https://ieltsliz.com/ielts-writing-task-2/", "IELTS Liz"],
  modelOpinion: ["Model essay: Opinion (agree/disagree)", "https://ieltsliz.com/ielts-agree-disagree-essay-sample-answer/", "IELTS Liz"],
  modelDiscussion: ["Model essay: Discussion", "https://ieltsliz.com/ielts-discussion-essay-model-answer/", "IELTS Liz"],
  modelSolution: ["Model essay: Problem / Solution", "https://ieltsliz.com/ielts-solution-essay-band-9-model-answer/", "IELTS Liz"],
  modelAdv: ["Model essay: Advantages / Disadvantages", "https://ieltsliz.com/ielts-advantage-disadvantage-model-essay/", "IELTS Liz"],
  modelDirect: ["Model essay: Direct questions (two questions)", "https://ieltsliz.com/ielts-model-essay-score-9/", "IELTS Liz"],
  masha: ["Formal vs Informal English Register", "https://www.mashaenglish.com/lessons/b2-formal-vs-informal", "MashaEnglish · B2"],
  tews: ["The English We Speak (everyday idioms)", "https://www.bbc.co.uk/learningenglish/english/features/the-english-we-speak", "", "tews"],
  bcMag: ["Magazine zone (B1–B2 reading)", "https://learnenglish.britishcouncil.org/free-resources/general/magazine-zone", "British Council"],
  conversation: ["The Conversation (articles by academics)", "https://theconversation.com/global", "", "conversation"],

  // ---------- Ngữ pháp: British Council ----------
  bcPresSimple: bc("grammar/a1-a2/present-simple", "Present simple"),
  bcStative: bc("grammar/b1-b2/stative-verbs", "Stative verbs"),
  bcPastCont: bc("grammar/a1-a2/past-continuous-past-simple", "Past continuous and past simple"),
  bcUsedTo: bc("grammar/b1-b2-grammar/past-habits-used-to-would-past-simple", "Past habits: used to, would and the past simple"),
  bcFuture: bc("grammar/b1-b2/future-forms-will-be-going-present-continuous", "Future forms: will, be going to and present continuous"),
  bcFutureCert: bc("grammar/b1-b2/future-degrees-certainty", "The future: degrees of certainty"),
  bcComparative: bc("grammar/a1-a2/comparative-adjectives", "Comparative adjectives"),
  bcModComp: bc("grammar/b1-b2/modifying-comparatives", "Modifying comparatives"),
  bcArticles: bc("grammar/a1-a2-grammar/articles-a-an-the", "Articles: a, an, the"),
  bcArticles2: bc("grammar/a1-a2-grammar/articles-the-or-no-article", "Articles: the or no article"),
  bcCountable: bc("grammar/a1-a2/nouns-countable-uncountable", "Nouns: countable and uncountable"),
  bcModalOblig: bc("grammar/b1-b2/modals-permission-obligation", "Modals: permission and obligation"),
  bcModalPres: bc("grammar/b1-b2/modals-deductions-about-present", "Modals: deductions about the present"),
  bcPrepPlace: bc("grammar/a1-a2/prepositions-place", "Prepositions of place: in, on, at"),
  bcPrepTime: bc("grammar/a1-a2-grammar/prepositions-of-time-at-in-on", "Prepositions of time: at, in, on"),
  bcAdjPrep: bc("grammar/a1-a2/adjectives-prepositions", "Adjectives and prepositions"),
  bcQuestions: bc("grammar/a1-a2/question-forms", "Question forms"),
  bcRelDef: bc("grammar/b1-b2/relative-clauses-defining-relative-clauses", "Relative clauses: defining"),
  bcRelNonDef: bc("grammar/b1-b2/relative-clauses-non-defining-relative-clauses", "Relative clauses: non-defining"),
  bcPresPerf: bc("grammar/b1-b2/present-perfect", "Present perfect"),
  bcPPyet: bc("grammar/b1-b2/present-perfect-just-yet-still-already", "Present perfect: just, yet, still, already"),
  bcPastPerf: bc("grammar/b1-b2/past-perfect", "Past perfect"),
  bcPPcont: bc("grammar/b1-b2/present-perfect-simple-continuous", "Present perfect simple and continuous"),
  bcCond012: bc("grammar/b1-b2/conditionals-zero-first-second", "Conditionals: zero, first and second"),
  bcRepState: bc("grammar/b1-b2/reported-speech-statements", "Reported speech: statements"),
  bcRepQ: bc("grammar/b1-b2/reported-speech-questions", "Reported speech: questions"),
  bcRepVerbs: bc("grammar/b1-b2/reported-speech-reporting-verbs", "Reported speech: reporting verbs"),
  bcPassives: bc("grammar/b1-b2/passives", "Passives"),
  bcIngInf: bc("grammar/a1-a2/verbs-followed-ing-or-infinitive", "Verbs followed by -ing or infinitive"),
  bcIngInf2: bc("grammar/b1-b2/verbs-followed-ing-or-infinitive-change-meaning", "Verbs followed by -ing or infinitive to change meaning"),
  bcModPast: bc("grammar/b1-b2/modals-deductions-about-past", "Modals: deductions about the past"),
  bcContrast: bc("grammar/b1-b2/contrasting-ideas-although-despite-others", "Contrasting ideas: although, despite and others"),
  bcPhrasal: bc("grammar/b1-b2/phrasal-verbs", "Phrasal verbs"),
  bcCond3: bc("grammar/b1-b2/conditionals-third-mixed", "Conditionals: third and mixed"),
  bcInvCond: bc("grammar/c1/inversion-conditionals", "Inversion and conditionals"),
  bcCleft: bc("grammar/c1/emphasis-cleft-sentences-inversion-auxiliaries", "Emphasis: cleft sentences, inversion and auxiliaries"),
  bcInvNeg: bc("grammar/c1/inversion-after-negative-adverbials", "Inversion after negative adverbials"),
  bcWish: bc("grammar/b1-b2/wishes-wish-if-only", "Wishes: wish and if only"),
  bcUnreal: bc("grammar/c1/unreal-time", "Unreal time"),
  bcAvoidRep: bc("grammar/c1/avoiding-repetition-text", "Avoiding repetition in a text"),
  bcWordOrderPV: bc("grammar/c1/word-order-phrasal-verbs", "Word order in phrasal verbs"),
  bcParticiple: bc("grammar/c1/participle-clauses", "Participle clauses"),
  bcContrastC1: bc("grammar/c1/contrasting-ideas", "Contrasting ideas (C1)"),
  bcModProb: bc("grammar/c1/modals-probability", "Modals: probability"),
  bcReportPatterns: bc("grammar/c1/patterns-reporting-verbs", "Patterns with reporting verbs"),
  bcAdvPassives: bc("grammar/c1/advanced-passives-review", "Advanced passives review"),

  // ---------- Ngữ pháp: video BBC Learning English ----------
  vPresent: yt("xFsYrTIndhI", "Present Simple and Present Continuous — 6 Minute Grammar", "BBC Learning English", 6),
  vPast: yt("uTB5I8V9Eog", "Past simple and past continuous — 6 Minute Grammar", "BBC Learning English", 6),
  vFuture: yt("jcAX1RtKq3U", "Talking about the future — 6 Minute Grammar", "BBC Learning English", 6),
  vFutureIAM: yt("T-L0BBB2icQ", "Will vs Be going to — English In a Minute", "BBC Learning English", 1),
  vComparative: yt("FAhpT7BH7GE", "Comparatives and superlatives — 6 Minute Grammar", "BBC Learning English", 6),
  vArticles: yt("ryRu8zFCKZE", "Articles — 6 Minute Grammar", "BBC Learning English", 6),
  vArticlesAbstract: yt("q-Jkx670rT8", "How to use the definite article with abstract uncountable nouns", "BBC Learning English", 6),
  vHaveToMust: yt("HUXXgVElADg", "'Have to' and 'must' — 6 Minute Grammar", "BBC Learning English", 6),
  vPrepTime: yt("UYjd9AU9jU8", "Prepositions of time — Prepositions with Georgie", "BBC Learning English", 3),
  vPrepPlace: yt("wkmKA2zGn6k", "Prepositions of place: in, at, on — English In A Minute", "BBC Learning English", 1),
  vQuestions: yt("j9b1CNN_rFU", "Asking questions — 6 Minute Grammar", "BBC Learning English", 6),
  vRelDef: yt("1iC_rULeuZc", "Defining relative clauses — 6 Minute Grammar", "BBC Learning English", 6),
  vPresPerf: yt("jwmKjgwlMk8", "Present perfect and past simple — 6 Minute Grammar", "BBC Learning English", 6),
  vForSince: yt("sSZcAh42qtI", "Present perfect with 'for' and 'since' — 6 Minute Grammar", "BBC Learning English", 6),
  vPastPerf: yt("vyvGJrB7WNM", "The past perfect tense — 6 Minute Grammar", "BBC Learning English", 6),
  vCond1: yt("8VETylIxyhw", "The first conditional — 6 Minute Grammar", "BBC Learning English", 6),
  vCond2: yt("3OuqzHxlrHc", "The second conditional — 6 Minute Grammar", "BBC Learning English", 6),
  vReported: yt("L-wTVCByxzk", "How to use reported speech — 6 Minute Grammar", "BBC Learning English", 6),
  vReportingVerbs: yt("Pu_3OgQxe2s", "Reporting verbs like 'insist', 'demand' and 'advise' — 6 Minute Vocabulary", "BBC Learning English", 6),
  vRelBoth: yt("ppyws3GdZ2E", "Using defining and non-defining relative clauses", "BBC Learning English", 6),
  vPassive: yt("38QqDrckyxM", "How to use the active and passive voice — 6 Minute Grammar", "BBC Learning English", 6),
  vVerbPatterns: yt("ohR163PgEK4", "Verb patterns — 6 Minute Grammar", "BBC Learning English", 6),
  vGerundInf: yt("LfDWCcbIjDg", "Gerund or infinitive? Ask BBC Learning English", "BBC Learning English", 5),
  vDeduction: yt("TWw8We_ElLo", "How to use modals of deduction and speculation — 6 Minute Grammar", "BBC Learning English", 6),
  vModalsPast: yt("1PY6xIDkIj4", "Modals in the past — BBC English Class", "BBC Learning English", 3),
  vContrast: yt("h8kBli8ZyX8", "How to use linking devices to show contrast", "BBC Learning English", 6),
  vLinking: yt("BECe_ok1RI8", "How to use linking words in English — English Masterclass", "BBC Learning English", 4),
  vPhrasalTypes: yt("FBmjH6nh5-k", "How to use phrasal verbs type 1, 2, 3 & 4 — 6 Minute Grammar", "BBC Learning English", 6),
  vPhrasals: yt("Gqu-bgwML00", "How to use phrasals — 6 Minute Grammar", "BBC Learning English", 6),
  vNarrative: yt("3mi5OI23A6w", "How to use narrative tenses — 6 Minute Grammar", "BBC Learning English", 6),
  vCond3: yt("pbm9IWNQmuM", "The third conditional — Conditionals with Georgie", "BBC Learning English", 4),
  vMixedCond: yt("_Mv7fBqauvc", "Mixing conditionals — English Masterclass", "BBC Learning English", 5),
  vInversion2: yt("RmQH6B9P8r8", "Inversion 2: reduced conditionals and more — English Masterclass", "BBC Learning English", 5),
  vEmphasis: yt("P7dcdEoNA_E", "Giving emphasis in English — English Masterclass", "BBC Learning English", 3),
  vWhatEmphasis: yt("-80zSEMCrgw", "Using 'what' to give emphasis — English Masterclass", "BBC Learning English", 5),
  vInversion1: yt("AzNxZGC-Hg0", "Inversion 1: after negative or limiting adverbs — English Masterclass", "BBC Learning English", 4),
  vWish: yt("LJcXRxy-nDU", "5 different ways to use 'wish' in English", "BBC Learning English", 5),
  vFormal: yt("hdKYl8Tg_FQ", "Formal English and informal English — English Masterclass", "BBC Learning English", 4),
  vSynonyms: yt("bdczLkc4Dns", "How to use English synonyms — 6 Minute Vocabulary", "BBC Learning English", 6),
  vSoften: yt("rQN4-l5AXE0", "Being polite: how to soften your English — English Masterclass", "BBC Learning English", 4),
  vParticiple: yt("H8E5EF0IEN0", "How to use participle clauses — English Masterclass", "BBC Learning English", 4),
  vLinkingWords: yt("j2YsroEPH5M", "How to use English linking words — 6 Minute Vocabulary", "BBC Learning English", 6),

  // ---------- Phát âm ----------
  pSchwa: yt("KwDJnXt3ZVQ", "Tim's Pronunciation Workshop: The schwa", "BBC Learning English", 3),
  pLinkCV: yt("mV_CEIroJs8", "Tim's pronunciation workshop: Consonant–vowel linking", "BBC Learning English", 3),
  pThIAM: yt("7CeNTtbhYLs", "Pronunciation of 'th' — English In A Minute", "BBC Learning English", 1),
  pThVoiceless: yt("b4Aj3k65HSo", "Voiceless /θ/ in 'thin', 'think', 'path'", "BBC Learning English", 1),
  pThVoiced: yt("tu1t3Fn5Lw8", "Voiced /ð/ in 'this', 'other', 'smooth'", "BBC Learning English", 1),
  pFinal: yt("WBVtja6Ee-8", "Final consonants — for Vietnamese learners of English (part 1)", "Smooth English", 5),
  pWordStress: yt("SGRIyLimIwU", "Stop Saying... Stress in long words", "BBC Learning English", 5),
  pLinkR: yt("wLprxwzWtc4", "The linking /r/ — Tim's pronunciation workshop", "BBC Learning English", 4),
  pLinkW: yt("cu-VK3JlgAk", "Pronunciation: Linking /w/", "BBC Learning English", 3),
  pLinkJ: yt("2Oi0NLl5Fdg", "Pronunciation: The linking /j/", "BBC Learning English", 4),
  pSentStress: yt("rnJCKda4oWU", "Sentence stress in English pronunciation", "Oxford Online English", 13),
  pTim4: tim(4, "Elision of /t/"),
  pTim3: tim(3, "'Twinning' or gemination"),
  pTim1: tim(1, "Assimilation of /t/ and /p/"),
  pTim16: tim(16, "Can"),
  pTim13: tim(13, "'was' and 'were'"),
  pTim12: tim(12, "And"),
  pTim11: tim(11, "Have to"),
  pTim26: tim(26, "Contracted 'have'"),
  pTim20: tim(20, "Been"),
  pTim18: tim(18, "The"),
  pTim22: tim(22, "From"),
  pTim30: tim(30, "Summary"),
  pIntonQ: yt("Aoj4HZlLQBY", "Questions and intonation: up or down?", "Rachel's English", 3),
  pStressTimed: yt("PrAe07KluZY", "English: a stress-timed language", "Rachel's English", 5),
  pShadowHow: yt("ljEP_ywBm7I", "Shadowing technique in English: are you wasting your time?", "Accent's Way English with Hadar", 16),

  // ---------- Kỹ năng IELTS ----------
  sPredict: yt("_6jgygopp40", "IELTS Listening tips: predicting answers", "IELTS Liz", 10),
  sForm: yt("3Gj2EGaLbrk", "IELTS Listening form completion", "E2 IELTS", 10),
  sTFNG: yt("WYl9PX7Ua_Q", "IELTS Reading tips: True False Not Given", "IELTS Liz", 24),
  sMap: yt("W1kuA2GuXks", "IELTS Listening map labelling", "E2 IELTS", 13),
  sLMC: yt("AkW0IeF46cA", "IELTS Listening tips: multiple choice", "IELTS Liz", 23),
  sParaphrase: yt("rlsqbSFOBCg", "Vocabulary for IELTS: paraphrasing tips", "IELTS Liz", 11),
  sMatchInfo: yt("V17YHaHAZ9U", "Matching paragraph information questions", "IELTS Worldly", 4),
  sHeadings: yt("7U91NAQzSys", "IELTS Reading: match headings", "E2 IELTS", 19),
  sTFNG2: yt("aLLTq-l0IeY", "Tips & strategies for True, False, Not Given", "E2 IELTS", 19),
  sRMC: yt("XuRfzG7zRzE", "IELTS Reading: multiple choice practice", "E2 IELTS", 9),
  sSentComp: yt("VMElU-C6DnA", "IELTS Reading sentence completion", "E2 IELTS", 12),
  sSentEnd: yt("FSkhLB3tSTg", "IELTS Reading methods: match sentence endings", "E2 IELTS", 10),
  sSummary: yt("cc9SOmmUQmI", "IELTS Reading summary completion tips", "IELTS with Juva", 14),
  sFeatures: yt("qrXRxIVZH3c", "IELTS Reading matching features & information", "Fastrack IELTS", 14),
  sHeadings2: yt("ETOdOzk0wGM", "IELTS Reading matching headings — strategy + practice", "English Pro Tips", 21),
  sTFNG3: yt("JkWwZt8UwA4", "IELTS Reading True–False–Not Given: strategy & practice", "Fastrack IELTS", 19),
  sRMC2: yt("CFXiTWdb4mY", "IELTS Reading: multiple choice questions", "Fastrack IELTS", 15),
  sLMC2: yt("as6l3Nw5eSs", "IELTS Listening multiple choice", "E2 IELTS", 18),
  sLMC3: yt("vpmJTSntyVw", "New strategy for IELTS Listening multiple choice", "IELTS Advantage", 12),
  sMapVocab: yt("_HomSxvEl24", "Phrases and vocabulary for IELTS map labelling", "E2 IELTS", 11),
  sLMC4: yt("3oQNETB8RdA", "IELTS Listening multiple choice: strategy & practice", "Fastrack IELTS", 26),
  sMapPractice: yt("l1LKp-q9k50", "IELTS Listening map labelling practice", "E2 IELTS", 11),
  sLEssential: yt("q8qmJeBxk4Q", "IELTS Listening tips & essential information", "IELTS Liz", 31),
  sLMC5: yt("3fJPAsRVCf4", "IELTS Listening: best strategy for multiple choice", "English Pro Tips", 14),

  // ---------- Writing Task 1 ----------
  wOverview: yt("zjzuxyVlkR8", "Writing Task 1: conclusion or overview", "IELTS Liz", 4),
  wOrganise: yt("TzLyARGcTEA", "Writing Task 1: how to organise your writing", "IELTS Liz", 3),
  wBar: yt("E3U1Y1jgGls", "Writing Task 1: how to describe a bar chart", "IELTS Liz", 18),
  wLine: yt("JxgA-qqw2m8", "IELTS line graph: 4 main complex sentence structures", "IELTS Liz", 8),
  wPie: yt("tgwibVefUKk", "IELTS Writing Task 1: pie charts", "IELTS Advantage", 24),
  wProcess: yt("LrsdF_1YNfs", "Task 1 process diagrams", "IELTS Advantage", 23),
  wTable: yt("bgO-qjK3l2A", "IELTS Academic Task 1 writing: tables", "Write to the Top", 11),
  wMap: yt("PhVlFDNAmUQ", "IELTS Writing Task 1 map vocabulary", "IELTS Liz", 10),
  wDataVocab: yt("MYjUEFeQv7w", "Writing Task 1: vocabulary for accurate data", "IELTS Liz", 5),
  wT1Intro: yt("oTe_2hmSHvw", "Writing Task 1 introduction paragraph", "IELTS Liz", 35),
  bcBarChart: bc("writing/b1/describing-bar-chart", "Describing a bar chart", "model"),
  bcCharts: bc("writing/b1/describing-charts", "Describing charts", "model"),
  bcLineGraph: bc("writing/b2/summary-line-graph", "A summary of a line graph", "model"),
  bcTwoCharts: bc("writing/b2/comparing-two-charts", "Comparing two charts", "model"),
  bcOpinionEssay: bc("writing/b2/opinion-essay", "An opinion essay", "model"),

  // ---------- Writing Task 2 ----------
  wIntro: yt("YngqHl_BLOU", "Writing Task 2: how to write an introduction", "IELTS Liz", 18),
  wParagraph: yt("y9Gn6aVRqaI", "Writing Task 2 essay: paragraph length", "IELTS Liz", 13),
  wExamples: yt("suu0KfL7jzs", "How to put examples in your essay", "IELTS Liz", 6),
  wOpinion: yt("SpAIW4p8wkw", "Writing Task 2 tips: expressing your opinion", "IELTS Liz", 6),
  wDiscussion: yt("gCo9L1nLlQ0", "Discussion essay: useful academic expressions", "IELTS Liz", 5),
  wPlan: yt("k5igP_H-C90", "How to plan an IELTS Writing Task 2 essay", "E2 IELTS", 6),
  wT2in5: yt("yvt8RzGNhBc", "Understand IELTS Writing Task 2 in 5 minutes", "IELTS Advantage", 6),

  // ---------- Speaking ----------
  spP1Topics: yt("QwDrJOpuMuA", "IELTS Speaking Part 1 topics", "IELTS Liz", 7),
  spP1Common: yt("E0jCDsWoM1A", "IELTS Speaking Part 1: common questions", "IELTS Liz", 7),
  spP2Start: yt("f5t8EQrg5dI", "IELTS Speaking Part 2: how to start your talk", "IELTS Liz", 5),
  spP3Urban: yt("KaK-VDFqgHc", "IELTS Speaking Part 3: urban vs rural life", "IELTS Liz", 11),
  spFluency: yt("owNwjiGd-RU", "IELTS Speaking: bands 5 to 8 — fluency and coherence", "IELTS by IDP", 6),
  sp7vs8: yt("XwgskILvIfU", "IELTS Speaking: band 7 vs band 8 — fluency and coherence", "IELTS by IDP", 3),
  spHome: yt("61izqh7ZBww", "How to improve your IELTS Speaking at home", "IELTS Liz", 13),
  spNonStop: yt("pXrqy0z3xoQ", "3 tips to speak non-stop for 2 minutes in Part 2", "Lilie IELTS", 12),
  spP3Convince: yt("TXXC7Wje8xE", "How to answer IELTS Speaking Part 3 convincingly", "The IELTS Workshop", 3),
  spP3Formula: yt("hOQ4ip_DAck", "IELTS Speaking Part 3: magic formula (topic: travel)", "IELTS with Charles", 6),
  spMakeover: yt("hTm282ohAg4", "A real IELTS Speaking makeover in 20 minutes", "IELTS Advantage", 26),
  spTest7: yt("YODIiPkVKAc", "IELTS Speaking band 7+ practice test", "IELTS with Charles", 13),
  spModel: yt("n5ohxW5lTIs", "IELTS Speaking test: practice & model answers", "IELTS Liz", 10),
  bcAgree: bc("speaking/b1/agreeing-disagreeing", "Agreeing and disagreeing", "videoEx"),
  bcAdvDis: bc("speaking/b2/discussing-advantages-disadvantages", "Discussing advantages and disadvantages", "videoEx"),
  bcChallenge: bc("speaking/b2/challenging-someones-ideas", "Challenging someone's ideas", "videoEx"),

  // ---------- 6 Minute English (1 tập/tuần) ----------
  e1: six("6-minute-english_2024/ep-241031", "Why you need a good night's sleep"),
  e2: six("6-minute-english_2025/ep-251225", "Was Christmas better in the past?"),
  e3: six("6-minute-english_2024/ep-240201", "What is the future of work?"),
  e4: six("6-minute-english_2026/ep-260521", "Making cities feel quieter"),
  e5: six("6-minute-english_2026/ep-260430", "Should we eat ultra-processed food?"),
  e6: six("6-minute-english_2024/ep-240912", "Keeping kids off smartphones"),
  e7: six("6-minute-english_2026/ep-260709", "Should we cycle more?"),
  e8: six("6-minute-english_2022/ep-221124", "The art of conversation"),
  e9: six("6-minute-english_2026/ep-260910", "Can apps teach you a language?"),
  e10: six("6-minute-english_2026/ep-260903", "Climate change and extreme weather"),
  e11: six("6-minute-english_2026/ep-260528", "Living with debt"),
  e12: six("6-minute-english_2026/ep-260108", "Is social media dead?"),
  e13: six("6-minute-english_2025/ep-250116", "Which country has the best schools?"),
  e14: six("6-minute-english_2024/ep-240229", "Plastic waste eaten by enzymes"),
  e15: six("6-minute-english_2025/ep-251113", "How important is play?"),
  e16: six("6-minute-english_2025/ep-251023", "Did a civilisation exist on Earth before humans?"),
  e17: six("6-minute-english_2025/ep-251009", "What makes a good citizen?"),
  e18: six("6-minute-english_2023/ep-230817", "Are you unhappy at work?"),
  e19: six("6-minute-english_2026/ep-260423", "Why are we all so stressed?"),
  e20: six("6-minute-english_2023/ep-230601", "Ecotourism: good or bad?"),
  e21: six("6-minute-english_2025/ep-250123", "How the world learned to love fast food"),
  e22: six("6-minute-english_2025/ep-250724", "What is degrowth?"),
  e23: six("6-minute-english_2024/ep-241219", "Call centres: Are you talking to AI?"),
  e24: six("6-minute-english_2026/ep-260820", "Sharing the road with driverless cars"),
  e25: six("6-minute-english_2025/ep-250703", "How do you say sorry?"),
  e26: six("6-minute-english_2025/ep-250213", "Rage bait: How online anger makes money"),
  e27: six("6-minute-english_2026/ep-260604", "The power of poetry"),
  e28: six("6-minute-english_2024/ep-241121", "The secrets to a healthy old age"),
  e29: six("6-minute-english_2024/ep-240711", "The school that puts the kids in charge"),
  e30: six("6-minute-english_2026/ep-260101", "Is it OK to disagree?"),
  e31: six("6-minute-english/ep-201112", "Could you be a victim of online fraud?"),
  e32: six("6-minute-english_2026/ep-260917", "Is rejection good for us?"),

  // ---------- British Council Reading ----------
  rStudySkills: bc("reading/a2/study-skills-tips", "Study skills tips (A2)"),
  rTravelGuide: bc("reading/b1/travel-guide", "A travel guide (B1)"),
  rRobotTeachers: bc("reading/b1/robot-teachers", "Robot teachers (B1)"),
  rDigitalHabits: bc("reading/b1/digital-habits-across-generations", "Digital habits across generations (B1)"),
  rForgetting: bc("reading/a2/infographic-forgetting-curve", "An infographic on the forgetting curve (A2)"),
  rFakeNews: bc("reading/b1/how-spot-fake-news", "How to spot fake news (B1)"),
  rConference: bc("reading/b1/conference-programme", "A conference programme (B1)"),
  rInfluencers: bc("reading/b1/social-media-influencers", "Social media influencers (B1)"),
  rInnovation: bc("reading/b1/innovation-business", "Innovation in business (B1)"),
  rPlasticOcean: bc("reading/b2/plastic-ocean-film-review", "A Plastic Ocean: a film review (B2)"),
  rBuyNothing: bc("reading/b2/buy-nothing-movement", "The Buy Nothing movement (B2)"),
  rShortStory: bc("reading/b2/short-story-extract", "A short story extract (B2)"),
  rMartian: bc("reading/b1/martian-book-review", "The Martian: a book review (B1)"),
  rBridges: bc("reading/b2/why-bridges-collapse", "Why bridges collapse (B2)"),
  rWorkLife: bc("reading/b2/work-life-balance", "Work–life balance (B2)"),
  rStarWars: bc("reading/b2/star-wars-hero-myth", "Star Wars and the hero myth (B2)"),
  rSharing: bc("reading/b2/sharing-economy", "The sharing economy (B2)"),
  rMillennials: bc("reading/b2/millennials-workplace", "Millennials in the workplace (B2)"),
  rLeadership: bc("reading/b2/cultural-expectations-leadership", "Cultural expectations and leadership (B2)"),
  rAsteroids: bc("reading/b2/asteroids", "Asteroids (B2)"),
  rBananas: bc("reading/c1/threat-bananas", "A threat to bananas (C1)"),
  rSupermarkets: bc("reading/c1/sustainable-supermarkets", "Sustainable supermarkets (C1)"),
  rMars: bc("reading/c1/life-mars", "Life on Mars (C1)"),
  rStateWorld: bc("reading/c1/state-world", "The state of the world (C1)"),
  rLanguage: bc("reading/c1/how-humans-evolved-language", "How humans evolved language (C1)"),
  rHorror: bc("reading/c1/horror-film-cliches", "Horror film clichés (C1)"),
  rBooks: bc("reading/c1/four-book-summaries", "Four book summaries (C1)"),
  rJornet: bc("reading/c1/biography-kilian-jornet", "A biography of Kilian Jornet (C1)"),
  rFeedback: bc("reading/c1/giving-receiving-positive-feedback", "Giving and receiving positive feedback (C1)"),
  rCulturalBiz: bc("reading/c1/cultural-behaviour-business", "Cultural behaviour in business (C1)"),
  rManifestos: bc("reading/c1/political-manifestos", "Political manifestos (C1)"),
  rManaging: bc("reading/c1/managing-problem", "Managing a problem (C1)"),

  // ---------- British Council Listening ----------
  lBriefing: bc("listening/a2/morning-briefing", "A morning briefing (A2)"),
  lMissingClass: bc("listening/a2/missing-class", "Missing a class (A2)"),
  lChangingPlans: bc("listening/a2/changing-plans", "Changing plans (A2)"),
  lFacts: bc("listening/a2/facts-figures", "Facts and figures (A2)"),
  lExplanation: bc("listening/a2/understanding-explanation", "Understanding an explanation (A2)"),
  lAssignment: bc("listening/a2/instructions-assignment", "Instructions for an assignment (A2)"),
  lTransport: bc("listening/a2/transport-announcements", "Transport announcements (A2)"),
  lOldFriend: bc("listening/b1/meeting-old-friend", "Meeting an old friend (B1)"),
  lLecture: bc("listening/b1/introduction-lecture", "An introduction to a lecture (B1)"),
  lWeather: bc("listening/b1/weather-forecast", "A weather forecast (B1)"),
  lDecision: bc("listening/b1/making-decision", "Making a decision (B1)"),
  lListeningSkills: bc("listening/b1/interview-about-listening-skills", "An interview about listening skills (B1)"),
  lStudentDiscussion: bc("listening/b1/student-discussion", "A student discussion (B1)"),
  lExperiment: bc("listening/b2/lecture-about-experiment", "A lecture about an experiment (B2)"),
  lDetox: bc("listening/b2/digital-detox-podcast", "A digital detox podcast (B2)"),
  lMotivation: bc("listening/b2/talk-about-motivation", "A talk about motivation (B2)"),
  lBizNews: bc("listening/b2/business-news", "Business news (B2)"),
  lDesign: bc("listening/b2/design-presentation", "A design presentation (B2)"),
  lAdvice: bc("listening/b2/getting-advice", "Getting advice (B2)"),
  lStudyGroup: bc("listening/b2/creating-study-group", "Creating a study group (B2)"),
  lInnovationC1: bc("listening/c1/innovation-business", "Innovation in business (C1)"),
  lHelix: bc("listening/c1/helix", "The helix (C1)"),
  lTechAddiction: bc("listening/c1/tech-addiction", "Tech addiction (C1)"),
  lRenting: bc("listening/c1/renting-house", "Renting a house (C1)"),
  lGestures: bc("listening/c1/history-hand-gestures", "The history of hand gestures (C1)"),
  lTwoBooks: bc("listening/c1/interview-about-two-books", "An interview about two books (C1)"),
  lCatchingUp: bc("listening/c1/catching-after-trip", "Catching up after a trip (C1)"),
  lBirthdays: bc("listening/c1/birthday-parties", "Birthday parties (C1)"),
  lProjectMeeting: bc("listening/c1/project-management-meeting", "A project management meeting (C1)"),
  lChallengesWork: bc("listening/c1/challenges-work", "Challenges at work (C1)"),
  lIntroverts: bc("listening/c1/introverts-redressing-balance", "Introverts – redressing the balance (C1)"),
  lJobInterview: bc("listening/c1/job-interview", "A job interview (C1)"),

  // ---------- TED-Ed (giai đoạn 1–2) & TED Talks (giai đoạn 3) ----------
  t1: yt("gedoSfZvBgE", "The benefits of a good night's sleep", "TED-Ed", 6),
  t2: yt("LaLvVc1sS20", "The history of tea", "TED-Ed", 5),
  t3: yt("RzkD_rTEBYs", "How will AI change the world?", "TED-Ed", 6),
  t4: yt("fKnAJCSGSdk", "Urbanization and the future of cities", "TED-Ed", 4),
  t5: yt("lEXBxijQREo", "How sugar affects the brain", "TED-Ed", 5),
  t6: yt("MMmOLN5zBLY", "The benefits of a bilingual brain", "TED-Ed", 5),
  t7: yt("TNokBgtSUvQ", "Why is there so much traffic?", "TED-Ed", 5),
  t8: yt("YmVpwXH4jhA", "How friendship affects your brain", "TED-Ed", 4),
  t9: yt("gCtlzT0HsZM", "What is the Internet, really?", "TED-Ed", 9),
  t10: yt("NCPTbfQyMt8", "Is the weather actually becoming more extreme?", "TED-Ed", 5),
  t11: yt("I5ZR0jMlxX0", "What causes economic bubbles?", "TED-Ed", 4),
  t12: yt("q-Y-z6HmRgI", "How to choose your news", "TED-Ed", 5),
  t13: yt("f2O6mQkFiiw", "How to practice effectively... for just about anything", "TED-Ed", 5),
  t14: yt("_6xlNyWPpB8", "What really happens to the plastic you throw away", "TED-Ed", 4),
  t15: yt("hmFQqjMF_f0", "How playing sports benefits your body ... and your brain", "TED-Ed", 4),
  t16: yt("fJBlEPOj4Fk", "How did they build the Great Pyramid of Giza?", "TED-Ed", 6),
  t17: yt("0fivQUlC7-8", "What did democracy really mean in Athens?", "TED-Ed", 5),
  t18: yt("FWTNMzK9vG4", "Why you procrastinate even when it feels bad", "TED-Ed", 6),
  t19: yt("v-t1Z5-oPtU", "How stress affects your body", "TED-Ed", 5),
  t20: yt("uBwkMc1llmM", "The incredible engineering of Venice", "TED-Ed", 7),
  t21: yt("hVimVzgtD6w", "Hans Rosling: The best stats you've ever seen", "TED", 21),
  t22: yt("BHY0FxzoKZE", "Wendy Suzuki: The brain-changing benefits of exercise", "TED", 13),
  t23: yt("arj7oStGLkU", "Tim Urban: Inside the mind of a master procrastinator", "TED", 14),
  t24: yt("R1vskiVDwl4", "Celeste Headlee: 10 ways to have a better conversation", "TED", 12),
  t25: yt("RKK7wGAYP6k", "Lera Boroditsky: How language shapes the way we think", "TED", 14),
  t26: yt("D9Ihs241zeg", "Chimamanda Ngozi Adichie: The danger of a single story", "TED", 19),
  t27: yt("eIho2S0ZahI", "Julian Treasure: How to speak so that people want to listen", "TED", 10),
  t28: yt("8KkKuTCFvzI", "Robert Waldinger: What makes a good life?", "TED", 13),
  t29: yt("iG9CE55wbtY", "Sir Ken Robinson: Do schools kill creativity?", "TED", 20),
  t30: yt("c0KYU2j0TM4", "Susan Cain: The power of introverts", "TED", 19),
  t31: yt("RcGyVTAoXEU", "Kelly McGonigal: How to make stress your friend", "TED", 14),
  t32: yt("H14bBuluwB8", "Angela Lee Duckworth: Grit", "TED", 6),
  t32b: yt("JnfBXjWm7hc", "Matt Cutts: Try something new for 30 days", "TED", 3),
};

// Sách cần mua: [số cuốn, tuần bắt đầu dùng]
const BOOKS = [[15, 1], [16, 5], [17, 16], [18, 20], [19, 24], [20, 28]];

// phase: 0 = chuẩn bị, 1 = nền tảng (5.0→5.5), 2 = vận dụng (5.5→6.5), 3 = tinh chỉnh (6.5→7.0)
// test: [cuốn Cambridge, số test] làm vào thứ Bảy; satMode: "fullLR" | "full" | "rest" (mặc định theo giai đoạn)
// t1.test / t1.rewrite: đề Writing Task 1 (rewrite = [cuốn, test, tuần đã thi]); t2.type: mã dạng bài Task 2
const WEEKS_BASE = [
  {
    n: 0,
    phase: 0,
  },
  {
    n: 1,
    phase: 1,
    grammar: "Present simple vs present continuous",
    gLinks: ["vPresent","bcPresSimple","bcStative"],
    topic: "Daily routines & sleep",
    six: "e1",
    col: ["get up early","stay up late","get enough sleep","stick to a routine","have a busy schedule","take a short break","feel refreshed","go to bed late"],
    read: "rStudySkills",
    listen: "lBriefing",
    ted: "t1",
    pron: ["pSchwa"],
    skill: ["sPredict","fmtL","fmtR"],
    sp: {
      "p1": [
        "Do you usually get up early?",
        "What do you normally do in the evening?",
        "Do you think you get enough sleep?",
        "What are you doing these days to stay healthy?"
      ]
    },
    test: [15,1],
  },
  {
    n: 2,
    phase: 1,
    grammar: "Past simple vs past continuous (+ used to)",
    gLinks: ["vPast","bcPastCont","bcUsedTo"],
    topic: "Past experiences & travel",
    six: "e2",
    col: ["go on a trip","set off early","book a hotel","miss a flight","get lost","take photos","have a great time","bring back memories"],
    read: "rTravelGuide",
    listen: "lMissingClass",
    ted: "t2",
    pron: ["pLinkCV"],
    skill: ["sForm"],
    sp: {
      "p1": [
        "Where did you go on your last holiday?",
        "What did you do last weekend?",
        "What did you use to do when you were a child?",
        "Do you prefer tea or coffee?"
      ]
    },
    test: [15,2],
  },
  {
    n: 3,
    phase: 1,
    grammar: "will / be going to / present continuous for the future",
    gLinks: ["vFuture","vFutureIAM","bcFuture","bcFutureCert"],
    topic: "Plans, goals & work",
    six: "e3",
    col: ["make plans","set a goal","apply for a job","change career","look forward to","get a promotion","work from home","run a business"],
    read: "rRobotTeachers",
    listen: "lChangingPlans",
    ted: "t3",
    pron: ["pThIAM","pThVoiceless","pThVoiced"],
    skill: ["sTFNG"],
    sp: {
      "p1": [
        "What are you going to do this weekend?",
        "Do you work or are you a student?",
        "What job would you like to do in the future?",
        "Do you like making plans?"
      ]
    },
    test: [15,3],
  },
  {
    n: 4,
    phase: 1,
    grammar: "Comparatives & superlatives (+ much/far/slightly)",
    gLinks: ["vComparative","bcComparative","bcModComp"],
    topic: "Cities & hometown",
    six: "e4",
    col: ["city centre","heavy traffic","public transport","cost of living","rush hour","green space","air pollution","densely populated"],
    read: "rDigitalHabits",
    listen: "lFacts",
    ted: "t4",
    pron: ["pFinal"],
    skill: ["sMap"],
    sp: {
      "p1": [
        "Where is your hometown?",
        "What do you like most about your hometown?",
        "Is your city a better place for young people or old people?",
        "How has your city changed in recent years?"
      ]
    },
    test: [15,4],
  },
  {
    n: 5,
    phase: 1,
    grammar: "Articles a/an/the/no article + countable/uncountable nouns",
    gLinks: ["vArticles","bcArticles","bcArticles2","bcCountable"],
    topic: "Food & health",
    six: "e5",
    col: ["a balanced diet","junk food","cut down on sugar","processed food","eat out","a home-cooked meal","put on weight","have a sweet tooth"],
    read: "rForgetting",
    listen: "lExplanation",
    ted: "t5",
    pron: ["pWordStress"],
    skill: ["sLMC"],
    sp: {
      "p1": [
        "What kind of food do you like?",
        "Do you often eat sweet things?",
        "Do you cook at home?",
        "Is fast food popular in your country?"
      ],
      "p2": "Describe a meal you really enjoyed. You should say: where you had it, who you were with, what you ate, and explain why you enjoyed it."
    },
    test: [16,1],
  },
  {
    n: 6,
    phase: 1,
    grammar: "Modals: must / have to / should / can / may / might",
    gLinks: ["vHaveToMust","bcModalOblig","bcModalPres"],
    topic: "Rules, school & learning",
    six: "e6",
    col: ["follow the rules","break a rule","make progress","pass an exam","fail a test","pay attention","learn by heart","do homework"],
    read: "rFakeNews",
    listen: "lAssignment",
    ted: "t6",
    pron: ["pLinkR"],
    skill: ["sParaphrase"],
    sp: {
      "p1": [
        "What languages can you speak?",
        "Did your school have many rules?",
        "What rules should children follow at home?",
        "Is learning English difficult for you?"
      ],
      "p2": "Describe a skill you would like to learn. You should say: what it is, why you want to learn it, how you would learn it, and explain how it would help you."
    },
    test: [16,2],
  },
  {
    n: 7,
    phase: 1,
    grammar: "Prepositions: in / on / at (time & place) + adjective + preposition",
    gLinks: ["vPrepTime","vPrepPlace","bcPrepTime","bcPrepPlace","bcAdjPrep"],
    topic: "Home & transport",
    six: "e7",
    col: ["take the bus","catch a train","get stuck in traffic","a traffic jam","commute to work","live in a flat","move house","on foot"],
    read: "rConference",
    listen: "lTransport",
    ted: "t7",
    pron: ["pLinkW","pLinkJ"],
    skill: ["sMatchInfo"],
    sp: {
      "p1": [
        "How do you usually travel to work or school?",
        "Is traffic a problem in your city?",
        "Do you live in a house or an apartment?",
        "What is your favourite room at home?"
      ],
      "p2": "Describe a journey you often make. You should say: where you go, how you travel, how long it takes, and explain how you feel about this journey."
    },
    test: [16,3],
  },
  {
    n: 8,
    phase: 1,
    grammar: "Question forms + defining relative clauses (who/which/that/where)",
    gLinks: ["vQuestions","vRelDef","bcQuestions","bcRelDef"],
    topic: "People & friendship",
    six: "e8",
    col: ["make friends","keep in touch","get on well with","have a lot in common","fall out with","lose touch","a close friend","spend time together"],
    read: "rInfluencers",
    listen: "lOldFriend",
    ted: "t8",
    pron: ["pSentStress"],
    skill: [],
    sp: {
      "p1": [
        "Do you have many close friends?",
        "How do you usually keep in touch with friends?",
        "What do you like doing with your friends?",
        "Do you prefer talking face to face or online?"
      ],
      "p2": "Describe a friend who is important to you. You should say: who this person is, how you met, what you do together, and explain why this friend is important to you."
    },
    test: [16,4],
    satMode: "fullLR",
  },
  {
    n: 9,
    phase: 2,
    grammar: "Present perfect vs past simple (+ for / since / just / yet / already)",
    gLinks: ["vPresPerf","vForSince","bcPresPerf","bcPPyet"],
    topic: "Technology",
    six: "e9",
    col: ["download an app","screen time","keep up with technology","access information","rely on technology","a digital device","go online","social media platform"],
    read: "rInnovation",
    listen: "lLecture",
    ted: "t9",
    pron: ["pTim4"],
    rskill: ["sHeadings"],
    speakVid: ["spP1Common"],
    satVid: ["sLMC2"],
    t1: {"links":["wOverview","wOrganise","bcCharts"],"test":[15,1]},
    t2: {"type":"opinion","prompt":"Some people believe that children under the age of 12 should not be allowed to own a smartphone. To what extent do you agree or disagree?","links":["wIntro","modelOpinion"]},
    sp: {
      "p1": [
        "How long have you had your current phone?",
        "Which apps have you used today?",
        "Have you ever lost your phone?",
        "Do you think you use your phone too much?"
      ],
      "p2": "Describe a piece of technology you have used for a long time. You should say: what it is, how long you have had it, what you use it for, and explain why it is important to you.",
      "p3": [
        "How has technology changed the way people communicate?",
        "Why do some older people find new technology difficult?",
        "What are the disadvantages of children using technology?"
      ]
    },
    test: [15,1],
  },
  {
    n: 10,
    phase: 2,
    grammar: "Past perfect + present perfect continuous",
    gLinks: ["vPastPerf","bcPastPerf","bcPPcont"],
    topic: "Environment",
    six: "e10",
    col: ["climate change","extreme weather","reduce waste","carbon emissions","renewable energy","protect the environment","global warming","natural disaster"],
    read: "rPlasticOcean",
    listen: "lWeather",
    ted: "t10",
    pron: ["pTim3"],
    rskill: ["sTFNG2"],
    speakVid: ["spP2Start"],
    satVid: ["sLMC3"],
    t1: {"links":["wBar","bcBarChart"],"test":[15,2]},
    t2: {"type":"problem","prompt":"In many cities, the amount of household waste is increasing rapidly. What are the causes of this problem, and what measures could be taken to solve it?","links":["wParagraph","modelSolution"]},
    sp: {
      "p1": [
        "Have you noticed any changes in the weather where you live?",
        "Do you recycle at home?",
        "Do you like spending time in nature?",
        "What kind of weather do you like best?"
      ],
      "p2": "Describe a time when you saw a lot of rubbish or plastic waste in a place. You should say: where it was, when it was, what you saw, and explain how you felt about it.",
      "p3": [
        "Who should be responsible for protecting the environment: individuals or governments?",
        "Why do many people still not recycle?",
        "Which environmental problems have become more serious in your country recently?"
      ]
    },
    test: [15,2],
  },
  {
    n: 11,
    phase: 2,
    grammar: "Zero, first and second conditionals",
    gLinks: ["vCond1","vCond2","bcCond012"],
    topic: "Money & shopping",
    six: "e11",
    col: ["save money","spend money on","get into debt","pay off a loan","a tight budget","earn a living","afford to buy","value for money"],
    read: "rBuyNothing",
    listen: "lDecision",
    ted: "t11",
    pron: ["pTim1"],
    rskill: ["sRMC"],
    speakVid: ["spP3Urban"],
    satVid: ["sMapVocab"],
    t1: {"links":["wLine","bcLineGraph"],"test":[15,3]},
    t2: {"type":"advdis","prompt":"More and more people are buying goods using 'buy now, pay later' schemes. Do the advantages of this development outweigh the disadvantages?","links":["wExamples","modelAdv"]},
    sp: {
      "p1": [
        "Do you enjoy shopping?",
        "Do you usually save money or spend it?",
        "If you had more free time, what would you do?",
        "What would you buy if you won some money?"
      ],
      "p2": "Describe something expensive you would like to buy in the future. You should say: what it is, how much it costs, why you want it, and explain how you would feel if you bought it.",
      "p3": [
        "Should children learn how to manage money at school?",
        "What will happen if people keep buying more than they need?",
        "Why do some people get into debt?"
      ]
    },
    test: [15,3],
  },
  {
    n: 12,
    phase: 2,
    grammar: "Reported speech: statements, questions & reporting verbs",
    gLinks: ["vReported","vReportingVerbs","bcRepState","bcRepQ","bcRepVerbs"],
    topic: "News & media",
    six: "e12",
    col: ["breaking news","fake news","a reliable source","go viral","spread misinformation","the mainstream media","a news headline","raise awareness"],
    read: "rShortStory",
    listen: "lListeningSkills",
    ted: "t12",
    pron: ["pTim16"],
    rskill: ["sSentComp"],
    speakVid: ["spFluency"],
    satVid: ["sLMC4"],
    t1: {"links":["bcTwoCharts","wDataVocab"],"test":[15,4]},
    t2: {"type":"discussion","prompt":"Some people think that news on social media is more useful than traditional newspapers and TV news, while others believe traditional sources are more reliable. Discuss both views and give your own opinion.","links":["wDiscussion","modelDiscussion"]},
    sp: {
      "p1": [
        "How do you usually get the news?",
        "Do you ever read newspapers?",
        "What kind of news interests you?",
        "Do you trust news on social media?"
      ],
      "p2": "Describe a piece of news you heard or read recently. You should say: what it was, where you heard or read it, who told you about it, and explain why it interested you.",
      "p3": [
        "How can people tell if a news story is fake?",
        "Should governments control what is published online?",
        "Why do some people prefer celebrity news to serious news?"
      ]
    },
    test: [15,4],
  },
  {
    n: 13,
    phase: 2,
    grammar: "Defining vs non-defining relative clauses",
    gLinks: ["vRelBoth","bcRelDef","bcRelNonDef"],
    topic: "Education",
    six: "e13",
    col: ["higher education","tuition fees","acquire knowledge","a degree in","critical thinking","hands-on experience","attend lectures","drop out of university"],
    read: "rMartian",
    listen: "lStudentDiscussion",
    ted: "t13",
    pron: ["pTim13"],
    rskill: ["sSentEnd"],
    speakVid: ["sp7vs8"],
    satVid: ["sMapPractice"],
    t1: {"links":["wPie"],"test":[16,1]},
    t2: {"type":"opinion","prompt":"Some people believe that university education should be free for all students. To what extent do you agree or disagree?","links":["wOpinion","modelOpinion","bcOpinionEssay"]},
    sp: {
      "p1": [
        "Which subject did you enjoy most at school?",
        "Who was a teacher that you liked?",
        "Do you prefer studying alone or with other people?",
        "Is there anything you would like to study in the future?"
      ],
      "p2": "Describe a teacher who had a big influence on you. You should say: who the teacher was, what subject they taught, what they were like, and explain why they influenced you.",
      "p3": [
        "What qualities does a good teacher need?",
        "Should university education be free?",
        "How will online learning change schools in the future?"
      ]
    },
    test: [16,1],
  },
  {
    n: 14,
    phase: 2,
    grammar: "Passives (present, past, perfect, modal passive)",
    gLinks: ["vPassive","bcPassives"],
    topic: "Science & how things are made",
    six: "e14",
    col: ["carry out research","conduct an experiment","make a discovery","scientific evidence","a breakthrough in","raw materials","the production process","be made from"],
    read: "rBridges",
    listen: "lExperiment",
    ted: "t14",
    pron: ["pTim12"],
    rskill: ["sSummary"],
    speakVid: ["spHome"],
    satVid: ["sLEssential"],
    t1: {"links":["wProcess"],"test":[16,2]},
    t2: {"type":"direct","prompt":"Scientific research is increasingly funded by private companies rather than governments. Why is this happening? Is this a positive or negative development?","links":["wPlan","modelDirect"]},
    sp: {
      "p1": [
        "Did you like science at school?",
        "What things are made in your city or region?",
        "Do you like watching documentaries?",
        "Do you know how your phone was made?"
      ],
      "p2": "Describe a useful invention. You should say: what it is, when it was invented, how it is used, and explain why you think it is useful.",
      "p3": [
        "Why is scientific research important?",
        "Should governments or private companies pay for research?",
        "How are products made differently today compared with the past?"
      ]
    },
    test: [16,2],
  },
  {
    n: 15,
    phase: 2,
    grammar: "Gerunds & infinitives (+ verbs that change meaning)",
    gLinks: ["vVerbPatterns","vGerundInf","bcIngInf","bcIngInf2"],
    topic: "Leisure & sport",
    six: "e15",
    col: ["do exercise","take up a hobby","play a sport","keep fit","a sedentary lifestyle","join a gym","in my spare time","give up (a hobby)"],
    read: "rWorkLife",
    listen: "lDetox",
    ted: "t15",
    pron: ["pTim11"],
    rskill: ["sFeatures"],
    speakVid: ["spNonStop"],
    satVid: ["sLMC5"],
    t1: {"links":["wTable"],"test":[16,3]},
    t2: {"type":"advdis","prompt":"Many young people now spend most of their free time playing video games rather than doing sport. What are the advantages and disadvantages of this trend?","links":["modelAdv"]},
    sp: {
      "p1": [
        "What do you enjoy doing in your free time?",
        "Do you like doing sport?",
        "Is there a hobby you would like to take up?",
        "Did you stop doing any hobbies as you got older?"
      ],
      "p2": "Describe a sport or activity you enjoy doing. You should say: what it is, when you started doing it, who you do it with, and explain why you enjoy it.",
      "p3": [
        "Why do some people stop exercising as they get older?",
        "Is it better for children to play sport or computer games?",
        "How can governments encourage people to be more active?"
      ]
    },
    test: [16,3],
  },
  {
    n: 16,
    phase: 2,
    grammar: "Modals of deduction: must have / might have / can't have + should have",
    gLinks: ["vDeduction","vModalsPast","bcModPast"],
    topic: "History & heritage",
    six: "e16",
    col: ["a historical site","an ancient civilisation","preserve heritage","cultural heritage","a historic building","a turning point","date back to","pass down traditions"],
    read: "rStarWars",
    listen: "lMotivation",
    ted: "t16",
    pron: ["pTim26"],
    rskill: ["sHeadings2"],
    speakVid: ["spP3Convince"],
    t1: {"links":["wMap"],"test":[16,4]},
    t2: {"type":"opinion","prompt":"Governments should spend money on preserving old buildings rather than constructing new ones. To what extent do you agree or disagree?","links":["modelOpinion"]},
    sp: {
      "p1": [
        "Do you like history?",
        "Have you visited any historical places?",
        "Do you enjoy going to museums?",
        "Which period of history would you like to know more about?"
      ],
      "p2": "Describe a historical place you have visited. You should say: where it is, when you went there, what you saw, and explain what you learned from the visit.",
      "p3": [
        "Why is it important to protect historical buildings?",
        "How might people have lived 500 years ago?",
        "Should history be a compulsory subject at school?"
      ]
    },
    test: [17,1],
    satMode: "fullLR",
  },
  {
    n: 17,
    phase: 2,
    grammar: "Although / despite / whereas / however / nevertheless",
    gLinks: ["vContrast","vLinking","bcContrast"],
    topic: "Society & government",
    six: "e17",
    col: ["the elderly","public services","social inequality","do voluntary work","take responsibility for","community spirit","the welfare system","contribute to society"],
    read: "rSharing",
    listen: "lBizNews",
    ted: "t17",
    pron: ["pTim20"],
    rskill: ["sTFNG3"],
    speakVid: ["spP3Formula"],
    t1: {"links":["wDataVocab","wT1Intro"],"test":[17,1]},
    t2: {"type":"discussion","prompt":"Some people think that the government should be responsible for looking after elderly people, while others believe this is the responsibility of their families. Discuss both views and give your own opinion.","links":["wDiscussion","modelDiscussion","diff67"]},
    sp: {
      "p1": [
        "Do you know your neighbours well?",
        "Have you ever done any volunteer work?",
        "Which public services do you use most often?",
        "Is your city a friendly place?"
      ],
      "p2": "Describe a time when you helped someone. You should say: who you helped, how you helped them, why you helped them, and explain how you felt afterwards.",
      "p3": [
        "Should the government or families look after elderly people?",
        "Why do some people not trust politicians?",
        "What makes a good citizen?"
      ]
    },
    test: [17,2],
    satMode: "full",
  },
  {
    n: 18,
    phase: 2,
    grammar: "Phrasal verbs (4 types, object position)",
    gLinks: ["vPhrasalTypes","bcPhrasal"],
    topic: "Work & careers",
    six: "e18",
    col: ["job satisfaction","a heavy workload","work-life balance","meet a deadline","climb the career ladder","take on responsibility","remote working","earn a salary"],
    read: "rMillennials",
    listen: "lDesign",
    ted: "t18",
    pron: ["pTim18"],
    rskill: ["sRMC2"],
    speakVid: ["spMakeover"],
    t1: {"links":["lizT1"],"test":[17,3]},
    t2: {"type":"direct","prompt":"Many people now work from home for at least part of the week. What are the reasons for this? Is it a positive or negative development?","links":["modelDirect"]},
    sp: {
      "p1": [
        "What do you do for a living?",
        "What do you like about your job or studies?",
        "Would you like to work from home?",
        "What time do you usually set off for work?"
      ],
      "p2": "Describe a job you would like to do in the future. You should say: what the job is, what skills it requires, how you could get this job, and explain why you would like to do it.",
      "p3": [
        "Is job satisfaction more important than salary?",
        "How will jobs change in the next 20 years?",
        "Why do some people change jobs often?"
      ]
    },
    test: [17,3],
    satMode: "fullLR",
  },
  {
    n: 19,
    phase: 2,
    gLinks: ["vNarrative","bcPresPerf","bcPastPerf","bcCond012","bcPassives"],
    topic: "Health & stress",
    six: "e19",
    col: ["mental health","cope with stress","a healthy lifestyle","lack of sleep","suffer from anxiety","seek help","burn out","relieve stress"],
    read: "rLeadership",
    listen: "lAdvice",
    ted: "t19",
    pron: ["pTim22"],
    rskill: [],
    speakVid: ["spTest7"],
    t1: {"links":[],"rewrite":[17,2,17]},
    t2: {"type":"problem","prompt":"Levels of stress among young adults are rising. What are the main causes of this, and what can be done to reduce it?","links":["modelSolution"]},
    sp: {
      "p1": [
        "Do you often feel stressed?",
        "What do you do to relax?",
        "Do you think you have a healthy lifestyle?",
        "How much exercise do you do each week?"
      ],
      "p2": "Describe a time when you felt very stressed. You should say: when it happened, why you felt stressed, what you did, and explain how you dealt with the situation.",
      "p3": [
        "Why are young people more stressed today than in the past?",
        "Should companies be responsible for their employees' mental health?",
        "What can schools do to reduce students' stress?"
      ]
    },
    test: [17,4],
    satMode: "full",
  },
  {
    n: 20,
    phase: 2,
    gLinks: [],
    topic: "Tourism",
    six: "e20",
    col: ["a tourist attraction","mass tourism","off the beaten track","the local economy","cultural exchange","the tourism industry","overcrowded","boost the economy"],
    read: "rAsteroids",
    listen: "lStudyGroup",
    ted: "t20",
    pron: ["pTim30"],
    rskill: [],
    speakVid: ["spModel"],
    t1: {"links":[],"rewrite":[17,4,19]},
    t2: {"type":"advdis","prompt":"International tourism has brought many benefits to developing countries, but it has also created problems. Do the advantages outweigh the disadvantages?","links":["modelAdv"]},
    sp: {
      "p1": [
        "Do you like travelling?",
        "Which places do tourists visit in your country?",
        "Do you prefer travelling alone or with other people?",
        "What do you usually do on holiday?"
      ],
      "p2": "Describe a place you visited that was crowded with tourists. You should say: where it was, when you went there, what you did there, and explain how you felt about the crowds.",
      "p3": [
        "What are the benefits of tourism for local people?",
        "In what ways can tourism damage a place?",
        "How will people travel in the future?"
      ]
    },
    test: [18,1],
    satMode: "full",
  },
  {
    n: 21,
    phase: 3,
    grammar: "Third & mixed conditionals",
    gLinks: ["vCond3","vMixedCond","bcCond3"],
    topic: "Globalisation",
    six: "e21",
    col: ["the global economy","cultural identity","multinational companies","lose its uniqueness","a global village","international trade","local traditions","Western influence"],
    read: "rBananas",
    listen: "lInnovationC1",
    ted: "t21",
    t2: {"type":"opinion","prompt":"As countries become more connected, local cultures are losing their uniqueness. To what extent do you agree or disagree?","links":["modelOpinion"]},
    sp: {
      "p1": [
        "Do you often eat food from other countries?",
        "Do you use many products made abroad?",
        "Would you like to live in another country?"
      ],
      "p2": "Describe an important decision you made. You should say: what the decision was, when you made it, why you made it, and explain how your life would be different if you had decided differently.",
      "p3": [
        "Does globalisation bring more benefits or more drawbacks?",
        "If international travel had never become cheap, how would the world be different?",
        "Why do some local traditions disappear?"
      ]
    },
    test: [18,2],
    satMode: "full",
  },
  {
    n: 22,
    phase: 3,
    grammar: "Cleft sentences (It is... that / What... is) + inverted conditionals (Had I known...)",
    gLinks: ["vEmphasis","vWhatEmphasis","vInversion2","bcCleft","bcInvCond"],
    topic: "Environment (advanced)",
    six: "e22",
    col: ["tackle climate change","sustainable development","reduce our carbon footprint","environmentally friendly","deforestation","the depletion of natural resources","impose a tax on","take drastic action"],
    read: "rSupermarkets",
    listen: "lHelix",
    ted: "t22",
    t2: {"type":"opinion","prompt":"Some people believe that individuals can do little to protect the environment and that only governments and large companies can make a real difference. To what extent do you agree or disagree?","links":["modelOpinion"]},
    sp: {
      "p1": [
        "Is your city clean?",
        "What do you do to save energy at home?",
        "Do you prefer the countryside or the city?"
      ],
      "p2": "Describe an environmental problem in your area. You should say: what it is, what causes it, how it affects people, and explain what could be done about it.",
      "p3": [
        "Is economic growth more important than protecting the environment?",
        "What is it that stops people from changing their habits?",
        "Will technology alone solve climate change?"
      ]
    },
    test: [18,3],
    satMode: "full",
  },
  {
    n: 23,
    phase: 3,
    grammar: "Inversion after negative adverbials (Not only... / Rarely... / Never before...)",
    gLinks: ["vInversion1","bcInvNeg"],
    topic: "Technology & AI",
    six: "e23",
    col: ["artificial intelligence","automate tasks","job displacement","data privacy","ethical concerns","human oversight","cutting-edge technology","digital literacy"],
    read: "rMars",
    listen: "lTechAddiction",
    ted: "t23",
    t2: {"type":"problem","prompt":"Artificial intelligence may soon replace many jobs that are currently done by people. What problems might this cause, and how could these problems be solved?","links":["modelSolution"]},
    sp: {
      "p1": [
        "Do you use AI tools in your daily life?",
        "Which website do you visit most often?",
        "Has technology made your life easier?"
      ],
      "p2": "Describe a time when a piece of technology stopped working when you needed it. You should say: what happened, when it happened, what you did, and explain how you felt.",
      "p3": [
        "Should AI be allowed to make important decisions, for example in medicine?",
        "Which skills will be most important in the future job market?",
        "Do the benefits of social media outweigh the problems it causes?"
      ]
    },
    test: [18,4],
    satMode: "full",
  },
  {
    n: 24,
    phase: 3,
    grammar: "Wish / if only / it's time / would rather",
    gLinks: ["vWish","bcWish","bcUnreal"],
    topic: "Cities & urbanisation",
    six: "e24",
    col: ["urban sprawl","rural-urban migration","a housing shortage","infrastructure","overcrowding","quality of life","affordable housing","urban planning"],
    read: "rStateWorld",
    listen: "lRenting",
    ted: "t24",
    t2: {"type":"advdis","prompt":"More and more people are moving from rural areas to big cities. Do the advantages of this trend outweigh the disadvantages?","links":["modelAdv"]},
    sp: {
      "p1": [
        "What would you change about your city?",
        "Do you wish you lived somewhere else?",
        "Is public transport good where you live?"
      ],
      "p2": "Describe a city you would like to live in. You should say: which city it is, how you know about it, what you would do there, and explain why you would like to live there.",
      "p3": [
        "Why do so many people move from the countryside to big cities?",
        "What problems do big cities face?",
        "How can cities be made more pleasant to live in?"
      ]
    },
    test: [19,1],
    satMode: "full",
  },
  {
    n: 25,
    phase: 3,
    grammar: "Register: formal vs informal language",
    gLinks: ["vFormal","masha","bcAvoidRep"],
    topic: "Language & communication",
    six: "e25",
    col: ["mother tongue","fluent in","a lingua franca","a language barrier","an endangered language","bilingual","pick up a language","formal register"],
    read: "rLanguage",
    listen: "lGestures",
    ted: "t25",
    t2: {"type":"discussion","prompt":"Some people think that everyone in the world should learn one global language, such as English. Others believe this could lead to the loss of other languages. Discuss both views and give your own opinion.","links":["modelDiscussion"]},
    sp: {
      "p1": [
        "How many languages do you speak?",
        "Do you speak differently to your friends and to your boss?",
        "Do you prefer texting or calling?"
      ],
      "p2": "Describe a time when you had difficulty communicating with someone. You should say: who it was, where you were, what the difficulty was, and explain how you solved the problem.",
      "p3": [
        "Is it necessary for everyone to learn English?",
        "How does our language change in formal situations?",
        "Will translation technology make learning languages unnecessary?"
      ]
    },
    test: [19,2],
    satMode: "full",
  },
  {
    n: 26,
    phase: 3,
    grammar: "Connotation, synonyms & avoiding repetition",
    gLinks: ["vSynonyms","bcAvoidRep","collocDict"],
    topic: "Media & advertising",
    six: "e26",
    col: ["target audience","persuasive techniques","consumer behaviour","brand loyalty","influencer marketing","impulse buying","misleading advertisements","an advertising campaign"],
    read: "rHorror",
    listen: "lTwoBooks",
    ted: "t26",
    t2: {"type":"opinion","prompt":"Advertising aimed at children should be banned. To what extent do you agree or disagree?","links":["modelOpinion"]},
    sp: {
      "p1": [
        "Do you pay attention to adverts?",
        "What was the last thing you bought because of an advert?",
        "Do you follow any influencers?"
      ],
      "p2": "Describe an advertisement you remember well. You should say: what it advertised, where you saw it, what it showed, and explain why you remember it.",
      "p3": [
        "Should advertising to children be controlled?",
        "How do advertisers persuade people to buy things?",
        "Are influencers more persuasive than traditional adverts?"
      ]
    },
    test: [19,3],
    satMode: "full",
  },
  {
    n: 27,
    phase: 3,
    gLinks: ["pStressTimed","pIntonQ","pShadowHow","pSentStress"],
    topic: "The arts",
    six: "e27",
    col: ["the performing arts","public funding","cultural value","artistic expression","a work of art","appreciate art","the visual arts","the creative industries"],
    read: "rBooks",
    listen: "lCatchingUp",
    ted: "t27",
    t2: {"type":"discussion","prompt":"Some people believe that government money should be spent on the arts, such as music and theatre, while others think it should be spent on more practical things, such as healthcare. Discuss both views and give your own opinion.","links":["modelDiscussion"]},
    sp: {
      "p1": [
        "Do you like poetry or music?",
        "Have you ever been to a concert?",
        "Did you learn any art at school?"
      ],
      "p2": "Describe a piece of music, a film or a book that moved you. You should say: what it was, when you first heard, saw or read it, what it is about, and explain why it affected you.",
      "p3": [
        "Should governments fund the arts?",
        "Why do people enjoy different types of art?",
        "Will AI-generated art replace human artists?"
      ]
    },
    test: [19,4],
    satMode: "full",
  },
  {
    n: 28,
    phase: 3,
    grammar: "Phrasal verbs: word order & meaning",
    gLinks: ["vPhrasals","bcWordOrderPV"],
    topic: "Family & ageing",
    six: "e28",
    col: ["an ageing population","life expectancy","the retirement age","an extended family","a nuclear family","care for elderly parents","the generation gap","the pension system"],
    read: "rJornet",
    listen: "lBirthdays",
    ted: "t28",
    t2: {"type":"problem","prompt":"In many countries, the proportion of older people is steadily increasing. What problems does this cause for society, and what solutions can you suggest?","links":["modelSolution"]},
    sp: {
      "p1": [
        "Do you spend a lot of time with your family?",
        "Who do you take after in your family?",
        "Do you get on well with your relatives?"
      ],
      "p2": "Describe an older person you admire. You should say: who this person is, how you know them, what they are like, and explain why you admire them.",
      "p3": [
        "What problems do societies with many old people face?",
        "Should adult children live with their elderly parents?",
        "What can young people learn from older people?"
      ]
    },
    test: [20,1],
    satMode: "full",
  },
  {
    n: 29,
    phase: 3,
    grammar: "Participle clauses (Having finished..., Built in 1990, ...)",
    gLinks: ["vParticiple","bcParticiple"],
    topic: "Education policy",
    six: "e29",
    col: ["the curriculum","academic performance","life skills","rote learning","compulsory subjects","vocational training","standardised tests","lifelong learning"],
    read: "rFeedback",
    listen: "lProjectMeeting",
    ted: "t29",
    t2: {"type":"discussion","prompt":"Some educators think that schools should focus on academic subjects, while others believe life skills, such as managing money, should also be taught. Discuss both views and give your own opinion.","links":["modelDiscussion","diff67"]},
    sp: {
      "p1": [
        "What did you like about your school?",
        "Do you think schools teach useful skills?",
        "Would you like to go back to studying?"
      ],
      "p2": "Describe a useful skill you learned outside school. You should say: what the skill is, how you learned it, how long it took, and explain why it is useful.",
      "p3": [
        "Should schools teach life skills such as managing money?",
        "Is creativity more important than exam results?",
        "How should teachers deal with students who have different abilities?"
      ]
    },
    test: [20,2],
    satMode: "full",
  },
  {
    n: 30,
    phase: 3,
    grammar: "Hedging & probability (It could be argued that..., is likely to...)",
    gLinks: ["vSoften","bcModProb","bcContrastC1"],
    topic: "Work & the economy",
    six: "e30",
    col: ["economic growth","productivity","flexible working hours","the unemployment rate","the labour market","self-employed","boost productivity","a four-day week"],
    read: "rCulturalBiz",
    listen: "lChallengesWork",
    ted: "t30",
    t2: {"type":"opinion","prompt":"Some people think that a four-day working week would benefit both employees and employers. To what extent do you agree or disagree?","links":["modelOpinion"]},
    sp: {
      "p1": [
        "Do you work long hours?",
        "What would you do with an extra day off each week?",
        "Do you prefer working in a team or alone?"
      ],
      "p2": "Describe a time when you disagreed with someone. You should say: who it was, what you disagreed about, how you handled it, and explain what happened in the end.",
      "p3": [
        "Would a four-day working week be good for the economy?",
        "Is it acceptable to disagree with your manager?",
        "Why do some people prefer to be self-employed?"
      ]
    },
    test: [20,3],
    satMode: "full",
  },
  {
    n: 31,
    phase: 3,
    gLinks: ["bcReportPatterns","bcAdvPassives"],
    topic: "Crime & society",
    six: "e31",
    col: ["commit a crime","the crime rate","a prison sentence","rehabilitation","deter crime","re-offend","community service","law enforcement"],
    read: "rManifestos",
    listen: "lIntroverts",
    ted: "t31",
    t2: {"type":"discussion","prompt":"Some people think that the best way to reduce crime is to give longer prison sentences. Others believe there are better alternatives. Discuss both views and give your own opinion.","links":["modelDiscussion"]},
    sp: {
      "p1": [
        "Do you feel safe in your city?",
        "Do you watch crime dramas?",
        "Have you ever lost something valuable?"
      ],
      "p2": "Describe a goal you have worked hard to achieve. You should say: what the goal was, why it was important, what you did to achieve it, and explain how you felt when you achieved it.",
      "p3": [
        "What makes people commit crimes?",
        "Is prison the best punishment for all crimes?",
        "How can technology help to prevent crime?"
      ]
    },
    test: [20,4],
    satMode: "full",
  },
  {
    n: 32,
    phase: 3,
    gLinks: [],
    topic: "Shopping & consumerism",
    six: "e32",
    col: ["online shopping","the high street","consumer spending","home delivery","compare prices","the retail industry","face-to-face service","e-commerce"],
    read: "rManaging",
    listen: "lJobInterview",
    ted: "t32",
    t2: {"type":"direct","prompt":"Online shopping is replacing shopping in stores. Is this a positive or negative development?","links":["modelDirect"]},
    sp: {
      "p1": [],
      "p2": "",
      "p3": []
    },
    satMode: "rest",
  },
];
